site_name: m4fc
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: m4fc
      handlers:
        python:
          options:
            docstring_style: numpy